# Generated by Django 4.2.2 on 2023-10-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datel', models.DateTimeField(auto_now_add=True, verbose_name='datel')),
                ('category', models.CharField(max_length=128, verbose_name='category')),
                ('details', models.TextField(blank=True, null=True, verbose_name='logfile_details')),
            ],
            options={
                'db_table': 'logfile',
                'ordering': ['datel'],
                'indexes': [models.Index(fields=['datel', 'category'], name='logfile_datel_2e4929_idx')],
            },
        ),
    ]
